numeros= [5, 4, 3, 2, 1] 

numeros.append(1.2)
numeros.append(5.5)
numeros.append(6.9)
numeros.append(2.1)
numeros.append(9.9)
print(numeros)
numeros.pop()
numeros.pop()
print(numeros)
print(len(numeros))
lista_decrescente = (sorted(numeros, reverse=True))
print(lista_decrescente)
print(max(numeros))
print(min(numeros))
print(sum(numeros))
print('media: ',sum(numeros) / len(numeros))
numeros.insert(0, 'achei facil')
print(numeros)
numeros.insert(1,'pra roncar tem que disbicar')
print(numeros)
